GET http://localhost:3001/api/blogs

###
POST http://localhost:3001/api/blogs
content-type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InNlY29uZFVzZXIiLCJpZCI6IjYwYzhlZjcxZDM2MWRiMjljNDY3OWYzZSIsImlhdCI6MTYyMzc4MjI5MH0.QZ8YQwu1OEAM9BDdTxsHxcRvTajTHwl3O4aidV0ggmQ

{
    "title": "anotherOne",
    "author": "arther",
    "url": "me.com"
}

###
POST http://localhost:3001/api/blogs
content-type: application/json

 {
    "author": "arther",
    "likes": 5
}
