GET http://localhost:3001/api/blogs

###
POST http://localhost:3001/api/blogs
content-type: application/json

{
    "title": "Tantalizing",
    "author": "arther",
    "url": "me.com",
    "likes": 5
}